apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-eljf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-eljf
    app.kubernetes.io/part-of: my-app
  name: devfile-sample-eljf
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-eljf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-eljf
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/karthik-jk-tenant/my-app/devfile-sample-eljf@sha256:bc5b7102a6915983cc30e2c27034ba2603c610115a3854262dbf4e0d5a5ef098
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
