apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-eljf
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/karthik-jk-tenant/my-app/devfile-sample-eljf@sha256:bc5b7102a6915983cc30e2c27034ba2603c610115a3854262dbf4e0d5a5ef098
        name: my-nodejs
        resources: {}
status: {}
